#ifndef CORE_LOCALIZATION_H
#define CORE_LOCALIZATION_H

enum localization_text_id {
  LOC_TEXT_COMMANDS_AVAILABLE = 0,
  LOC_TEXT_NO_COMMANDS_REGISTERED,
  LOC_TEXT_HELP_DOCS_HINT,
  LOC_TEXT_DOCS_NOT_FOUND,
  LOC_TEXT_DOCS_VERIFY_INSTALL,
  LOC_TEXT_LOGOUT_MESSAGE,
  LOC_TEXT_UNKNOWN_COMMAND_PREFIX,
  LOC_TEXT_UNKNOWN_COMMAND_HINT,
  LOC_TEXT_NO_INPUT_DEVICE,
  LOC_TEXT_PREPARE_SHELL_FAILED,
  LOC_TEXT_AUTH_FLOW_FAILED,
  LOC_TEXT_SESSION_ACTIVATION_FAILED,
  LOC_TEXT_RETURNING_TO_LOGIN,
  LOC_TEXT_WELCOME_PREFIX,
  LOC_TEXT_LAYOUT_CURRENT,
  LOC_TEXT_LAYOUT_LIST_HEADER,
  LOC_TEXT_LAYOUT_UNKNOWN,
  LOC_TEXT_LAYOUT_UPDATED,
  LOC_TEXT_LAYOUT_UPDATED_SAVED,
  LOC_TEXT_THEME_CURRENT,
  LOC_TEXT_THEME_LIST_HEADER,
  LOC_TEXT_THEME_UNKNOWN,
  LOC_TEXT_THEME_UPDATED,
  LOC_TEXT_THEME_UPDATED_SAVED,
  LOC_TEXT_CONFIG_SAVE_WARNING,
  LOC_TEXT_SPLASH_CURRENT,
  LOC_TEXT_SPLASH_UNKNOWN,
  LOC_TEXT_SPLASH_UPDATED,
  LOC_TEXT_SPLASH_UPDATED_ON,
  LOC_TEXT_SPLASH_UPDATED_OFF,
  LOC_TEXT_LANGUAGE_CURRENT,
  LOC_TEXT_LANGUAGE_LIST_HEADER,
  LOC_TEXT_LANGUAGE_UNKNOWN,
  LOC_TEXT_LANGUAGE_UPDATED,
  LOC_TEXT_LANGUAGE_UPDATED_SAVED,
};

const char *localization_normalize_language(const char *input);
int localization_language_supported(const char *input);
const char *localization_text_for(const char *language,
                                  enum localization_text_id id);
const char *localization_language_label(const char *language);
const char *localization_language_name(const char *language);

#endif
