#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from build_modules_index import (
    DEFAULT_REPOS,
    ManifestError,
    emit_entry,
    find_manifest_files,
    parse_manifest,
    validate_manifest,
)

LOCAL_BASE_URL = "https://local.capyos.invalid/capypkg/"
LOCAL_INDEX_NAME = "modules-index.txt"


class BundleError(RuntimeError):
    pass


def payload_basename(url: str) -> str:
    name = url.rstrip("/").rsplit("/", 1)[-1]
    if not name or name in (".", "..") or "/" in name or "\\" in name:
        raise BundleError(f"invalid payload_url basename: {url!r}")
    return name


def local_payload_path(manifest: Path, fields: Dict[str, str]) -> Path:
    basename = payload_basename(fields["payload_url"])
    direct = manifest.parent / basename
    if direct.is_file():
        return direct
    fallback = manifest.parent / f"{fields['name']}-{fields['version']}.bin"
    if fallback.is_file():
        return fallback
    raise BundleError(f"{manifest}: local payload not found for {basename!r}")


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_payload(path: Path, fields: Dict[str, str], manifest: Path) -> bytes:
    data = path.read_bytes()
    expected_size = fields.get("payload_size", "")
    if expected_size and int(expected_size) != len(data):
        raise BundleError(
            f"{manifest}: payload_size={expected_size} but {path} has {len(data)} bytes"
        )
    actual_sha = hashlib.sha256(data).hexdigest()
    if actual_sha != fields["payload_sha256"]:
        raise BundleError(
            f"{manifest}: payload_sha256 mismatch for {path} "
            f"actual={actual_sha} expected={fields['payload_sha256']}"
        )
    return data


def c_identifier(seed: str) -> str:
    out = re.sub(r"[^a-zA-Z0-9_]", "_", seed)
    if not out or out[0].isdigit():
        out = f"blob_{out}"
    return out


def c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_bytes(data: bytes) -> str:
    if not data:
        return "0"
    lines: List[str] = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}u" for b in chunk) + ",")
    return "\n".join(lines)


def build_bundle(workspace: Path, repos: List[str], base_url: str) -> Tuple[str, List[Tuple[str, bytes]]]:
    index_lines: List[str] = [
        "# CapyOS local lab modules index, generated by build_local_capypkg_bundle.py",
        "# This index is for pre-release local ISO testing only.",
    ]
    payloads: List[Tuple[str, bytes]] = []
    seen_urls: set[str] = set()
    total = 0
    for repo in repos:
        manifests = find_manifest_files(workspace, repo)
        if not manifests:
            print(f"[warn] {repo}: no capypkg manifest found", file=sys.stderr)
            continue
        for manifest in manifests:
            fields = parse_manifest(manifest)
            validate_manifest(manifest, fields)
            payload_path = local_payload_path(manifest, fields)
            payload_data = verify_payload(payload_path, fields, manifest)
            basename = payload_basename(fields["payload_url"])
            local_url = f"{base_url.rstrip('/')}/{basename}"
            if local_url in seen_urls:
                raise BundleError(f"duplicate local payload URL: {local_url}")
            seen_urls.add(local_url)
            rewritten = dict(fields)
            rewritten["payload_url"] = local_url
            rewritten.setdefault("official", "1")
            validate_manifest(manifest, rewritten)
            emit_entry(rewritten, index_lines)
            payloads.append((local_url, payload_data))
            total += 1
            print(f"[ok] {repo}: {rewritten['name']}@{rewritten['version']} -> {local_url}")
    if total == 0:
        raise BundleError("no local manifests aggregated")
    return "\n".join(index_lines) + "\n", payloads


def write_outputs(
    index_text: str,
    payloads: List[Tuple[str, bytes]],
    output_index: Path,
    output_c: Optional[Path],
    output_h: Optional[Path],
    base_url: str,
) -> None:
    output_index.parent.mkdir(parents=True, exist_ok=True)
    output_index.write_text(index_text, encoding="utf-8")
    print(f"[ok] wrote local index to {output_index}")
    if not output_c and not output_h:
        return
    if not output_c or not output_h:
        raise BundleError("--output-c and --output-h must be provided together")
    output_c.parent.mkdir(parents=True, exist_ok=True)
    output_h.parent.mkdir(parents=True, exist_ok=True)
    blobs: List[Tuple[str, str, bytes]] = [
        (f"{base_url.rstrip('/')}/{LOCAL_INDEX_NAME}", "modules_index", index_text.encode("utf-8"))
    ]
    for url, data in payloads:
        blobs.append((url, c_identifier(payload_basename(url)), data))
    h_text = "\n".join([
        "#ifndef CAPYPKG_LOCAL_BUNDLE_DATA_H",
        "#define CAPYPKG_LOCAL_BUNDLE_DATA_H",
        "",
        "#include \"services/capypkg_local_bundle.h\"",
        "",
        "extern const struct capypkg_local_bundle_blob capypkg_local_bundle_blobs[];",
        "extern const size_t capypkg_local_bundle_blob_count;",
        "",
        "#endif",
        "",
    ])
    c_lines: List[str] = [
        "#include \"services/capypkg_local_bundle.h\"",
        "#include \"capypkg_local_bundle_data.h\"",
        "",
    ]
    used_names: Dict[str, int] = {}
    emitted: List[Tuple[str, str, int]] = []
    for url, seed, data in blobs:
        count = used_names.get(seed, 0)
        used_names[seed] = count + 1
        ident = f"capypkg_local_blob_{seed}" if count == 0 else f"capypkg_local_blob_{seed}_{count}"
        c_lines.append(f"static const uint8_t {ident}[] = {{")
        c_lines.append(c_bytes(data))
        c_lines.append("};")
        c_lines.append("")
        emitted.append((url, ident, len(data)))
    c_lines.append("const struct capypkg_local_bundle_blob capypkg_local_bundle_blobs[] = {")
    for url, ident, _ in emitted:
        c_lines.append(f"    {{{c_string(url)}, {ident}, sizeof({ident})}},")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append(
        "const size_t capypkg_local_bundle_blob_count = "
        "sizeof(capypkg_local_bundle_blobs) / sizeof(capypkg_local_bundle_blobs[0]);"
    )
    c_lines.append("")
    output_h.write_text(h_text, encoding="utf-8")
    output_c.write_text("\n".join(c_lines), encoding="utf-8")
    print(f"[ok] wrote local bundle header to {output_h}")
    print(f"[ok] wrote local bundle source to {output_c}")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build a CapyOS local capypkg bundle.")
    parser.add_argument("--workspace", default=None)
    parser.add_argument("--repos", nargs="+", default=list(DEFAULT_REPOS))
    parser.add_argument("--base-url", default=LOCAL_BASE_URL)
    parser.add_argument("--output-index", default="build/capypkg/local/modules-index.txt")
    parser.add_argument("--output-c", default=None)
    parser.add_argument("--output-h", default=None)
    args = parser.parse_args(argv)

    capyos_root = Path(__file__).resolve().parent.parent.parent
    workspace = Path(args.workspace) if args.workspace else capyos_root.parent
    output_index = Path(args.output_index)
    if not output_index.is_absolute():
        output_index = capyos_root / output_index
    output_c = Path(args.output_c) if args.output_c else None
    if output_c and not output_c.is_absolute():
        output_c = capyos_root / output_c
    output_h = Path(args.output_h) if args.output_h else None
    if output_h and not output_h.is_absolute():
        output_h = capyos_root / output_h

    try:
        index_text, payloads = build_bundle(workspace, args.repos, args.base_url)
        write_outputs(index_text, payloads, output_index, output_c, output_h, args.base_url)
    except (BundleError, ManifestError, OSError, ValueError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
