#include <stdio.h>

int run_block_wrapper_tests(void);
int run_partition_tests(void);
int run_keyboard_layout_tests(void);
int run_grub_cfg_builder_tests(void);
int run_boot_manifest_tests(void);
int run_boot_writer_tests(void);
int run_csprng_tests(void);
int run_crypt_vector_tests(void);
int run_volume_header_tests(void);
int run_volume_provider_tests(void);
int run_volume_provider_execute_tests(void);
int run_volume_provider_rekey_execute_tests(void);
int run_volume_provider_rekey_commit_tests(void);
int run_volume_provider_rekey_recovery_tests(void);
int run_volume_provider_rekey_orchestrator_tests(void);
int run_user_password_hash_tests(void);
int run_efi_block_tests(void);
int run_klog_tests(void);
int run_auth_policy_tests(void);
int run_login_runtime_tests(void);
int run_loginwindow_auth_submit_tests(void);
int run_loginwindow_recovery_decision_tests(void);
int run_loginwindow_session_handoff_tests(void);
int run_localization_tests(void);
int run_capyfs_check_tests(void);
int run_service_manager_tests(void);
int run_service_boot_policy_tests(void);
int run_work_queue_tests(void);
int run_update_agent_tests(void);
int run_audit_events_tests(void);
int run_journal_tests(void);
int run_capyfs_journal_cause_tests(void);
int run_update_transact_tests(void);
int run_gen_boot_config_tests(void);
int run_user_home_tests(void);
int run_http_encoding_tests(void);
int run_net_dns_tests(void);
int run_net_probe_tests(void);
int run_hyperv_runtime_tests(void);
int run_hyperv_runtime_gate_tests(void);
int run_hyperv_runtime_policy_tests(void);
int run_input_hyperv_gate_tests(void);
int run_native_runtime_gate_tests(void);
int run_netvsc_backend_tests(void);
int run_netvsc_runtime_tests(void);
int run_netvsc_session_tests(void);
int run_netvsp_tests(void);
int run_netvsc_control_tests(void);
int run_rndis_tests(void);
int run_storvsp_tests(void);
int run_storvsc_session_tests(void);
int run_storvsc_backend_tests(void);
int run_storvsc_runtime_tests(void);
int run_storage_runtime_hyperv_plan_tests(void);

int test_pmm_run(void);
int test_task_run(void);
int test_task_iter_run(void);
int test_task_stats_run(void);
int test_process_iter_run(void);
int test_process_destroy_run(void);
int test_vmm_anon_regions_run(void);
int test_service_runner_run(void);
int test_context_switch_run(void);
int test_syscall_msr_run(void);
int test_fault_classify_run(void);
int test_pmm_refcount_run(void);
int test_vmm_cow_run(void);
int test_tss_layout_run(void);
int test_user_task_init_run(void);
int test_cpu_local_run(void);
int test_enter_user_mode_run(void);
int test_capylibc_abi_run(void);
int test_hello_program_run(void);
int test_user_init_run(void);
int test_embedded_progs_run(void);
int test_pipe_run(void);
int test_linux_clock_run(void);
int test_linux_syscall_run(void);
int test_linux_random_run(void);
int test_linux_devfs_run(void);
int test_linux_process_run(void);
int test_linux_cpuinfo_run(void);
int test_linux_proc_run(void);
int test_linux_fd_run(void);
int test_linux_mmap_run(void);
int test_linux_futex_run(void);
int test_linux_eventfd_run(void);
int test_linux_net_run(void);
int test_linux_epoll_run(void);
int test_linux_signal_run(void);
int test_linux_memfd_run(void);
int test_linux_inotify_run(void);
int test_linux_clone_run(void);
int test_linux_shm_run(void);
int test_linux_vfs_run(void);
int test_linux_vfs_router_run(void);
int test_linux_procfs_run(void);
int test_linux_tmpfs_run(void);
int test_linux_brk_run(void);
int test_linux_arch_prctl_run(void);
int test_linux_exit_run(void);
int test_linux_ioctl_run(void);
int test_linux_fcntl_run(void);
int test_linux_io_run(void);
int test_linux_stat_run(void);
int test_linux_path_run(void);
int test_linux_statx_run(void);
int test_linux_dirent_run(void);
int test_linux_at_run(void);
int test_linux_dup_run(void);
int test_linux_umask_run(void);
int test_linux_wait_run(void);
int test_linux_kill_run(void);
int test_linux_trunc_run(void);
int test_linux_sysinfo_run(void);
int test_linux_priority_run(void);
int test_linux_pgrp_run(void);
int test_linux_fs_mut_run(void);
int test_linux_mlock_run(void);
int test_linux_creds_run(void);
int test_linux_fs_meta_run(void);
int test_linux_link_run(void);
int test_linux_sync_run(void);
int test_linux_utime_run(void);
int test_linux_setid_run(void);
int test_linux_chdir_run(void);
int test_linux_xattr_run(void);
int test_linux_statfs_run(void);
int test_linux_advise_run(void);
int test_linux_rlimit_legacy_run(void);
int test_linux_caps_run(void);
int test_linux_itimer_run(void);
int test_linux_lock_run(void);
int test_linux_sched_prio_run(void);
int test_linux_posix_timer_run(void);
int test_linux_time_legacy_run(void);
int test_linux_sandbox_run(void);
int test_linux_mincore_run(void);
int test_linux_numa_run(void);
int test_linux_settod_run(void);
int test_linux_jit_aux_run(void);
int test_linux_namespace_run(void);
int test_linux_exec_ext_run(void);
int test_linux_pipe_zero_run(void);
int test_linux_proc_vm_run(void);
int test_linux_openat2_run(void);
int test_linux_pkey_run(void);
int test_linux_landlock_run(void);
int test_linux_seccomp_run(void);
int test_linux_fanotify_run(void);
int test_linux_io_uring_run(void);
int test_linux_modern_misc_run(void);
int test_stdin_buf_run(void);
int test_gui_event_run(void);
int test_compositor_events_run(void);
int test_gui_window_dispatcher_run(void);
int test_desktop_smoke_readiness_run(void);
int test_dns_cache_run(void);
int test_tls_hostname_run(void);
int test_boot_slot_run(void);
int run_op_budget_tests(void);
int run_privilege_tests(void);
int run_buffer_cache_pacing_tests(void);
int test_syscall_pipe_priority_run(void);
int test_syscall_net_run(void);
int test_capylibc_net_run(void);
int test_capylibc_tls_run(void);
int test_syscall_net_init_run(void);
int test_process_current_dynamic_run(void);

int main(void) {
    int failures = 0;
    failures += run_block_wrapper_tests();
    failures += run_partition_tests();
    failures += run_keyboard_layout_tests();
    failures += run_grub_cfg_builder_tests();
    failures += run_boot_manifest_tests();
    failures += run_boot_writer_tests();
    failures += run_csprng_tests();
    failures += run_crypt_vector_tests();
    failures += run_volume_provider_tests();
    failures += run_volume_provider_execute_tests();
    failures += run_volume_provider_rekey_execute_tests();
    failures += run_volume_provider_rekey_commit_tests();
    failures += run_volume_provider_rekey_recovery_tests();
    failures += run_volume_provider_rekey_orchestrator_tests();
    failures += run_volume_header_tests();
    failures += run_user_password_hash_tests();
    failures += run_efi_block_tests();
    failures += run_klog_tests();
    failures += run_auth_policy_tests();
    failures += run_login_runtime_tests();
    failures += run_loginwindow_auth_submit_tests();
    failures += run_loginwindow_recovery_decision_tests();
    failures += run_loginwindow_session_handoff_tests();
    failures += run_localization_tests();
    failures += run_capyfs_check_tests();
    failures += run_service_manager_tests();
    failures += run_service_boot_policy_tests();
    failures += run_work_queue_tests();
    failures += run_update_agent_tests();
    failures += run_audit_events_tests();
    failures += run_journal_tests();
    failures += run_capyfs_journal_cause_tests();
    failures += run_update_transact_tests();
    failures += run_gen_boot_config_tests();
    failures += run_user_home_tests();
    failures += run_http_encoding_tests();
    failures += run_net_dns_tests();
    failures += run_net_probe_tests();
    failures += run_hyperv_runtime_tests();
    failures += run_hyperv_runtime_gate_tests();
    failures += run_hyperv_runtime_policy_tests();
    failures += run_input_hyperv_gate_tests();
    failures += run_native_runtime_gate_tests();
    failures += run_netvsc_backend_tests();
    failures += run_netvsc_runtime_tests();
    failures += run_netvsc_session_tests();
    failures += run_netvsp_tests();
    failures += run_netvsc_control_tests();
    failures += run_rndis_tests();
    failures += run_storvsp_tests();
    failures += run_storvsc_session_tests();
    failures += run_storvsc_backend_tests();
    failures += run_storvsc_runtime_tests();
    failures += run_storage_runtime_hyperv_plan_tests();

    failures += test_pmm_run();
    failures += test_task_run();
    failures += test_task_iter_run();
    failures += test_task_stats_run();
    failures += test_process_iter_run();
    failures += test_process_destroy_run();
    failures += test_vmm_anon_regions_run();
    failures += test_service_runner_run();
    failures += test_context_switch_run();
    failures += test_syscall_msr_run();
    failures += test_fault_classify_run();
    failures += test_pmm_refcount_run();
    failures += test_vmm_cow_run();
    failures += test_tss_layout_run();
    failures += test_user_task_init_run();
    failures += test_cpu_local_run();
    failures += test_enter_user_mode_run();
    failures += test_capylibc_abi_run();
    failures += test_hello_program_run();
    failures += test_user_init_run();
    failures += test_embedded_progs_run();
    failures += test_pipe_run();
    failures += test_linux_clock_run();
    failures += test_linux_syscall_run();
    failures += test_linux_random_run();
    failures += test_linux_devfs_run();
    failures += test_linux_process_run();
    failures += test_linux_cpuinfo_run();
    failures += test_linux_proc_run();
    failures += test_linux_fd_run();
    failures += test_linux_mmap_run();
    failures += test_linux_futex_run();
    failures += test_linux_eventfd_run();
    failures += test_linux_net_run();
    failures += test_linux_epoll_run();
    failures += test_linux_signal_run();
    failures += test_linux_memfd_run();
    failures += test_linux_inotify_run();
    failures += test_linux_clone_run();
    failures += test_linux_shm_run();
    failures += test_linux_vfs_run();
    failures += test_linux_vfs_router_run();
    failures += test_linux_procfs_run();
    failures += test_linux_tmpfs_run();
    failures += test_linux_brk_run();
    failures += test_linux_arch_prctl_run();
    failures += test_linux_exit_run();
    failures += test_linux_ioctl_run();
    failures += test_linux_fcntl_run();
    failures += test_linux_io_run();
    failures += test_linux_stat_run();
    failures += test_linux_path_run();
    failures += test_linux_statx_run();
    failures += test_linux_dirent_run();
    failures += test_linux_at_run();
    failures += test_linux_dup_run();
    failures += test_linux_umask_run();
    failures += test_linux_wait_run();
    failures += test_linux_kill_run();
    failures += test_linux_trunc_run();
    failures += test_linux_sysinfo_run();
    failures += test_linux_priority_run();
    failures += test_linux_pgrp_run();
    failures += test_linux_fs_mut_run();
    failures += test_linux_mlock_run();
    failures += test_linux_creds_run();
    failures += test_linux_fs_meta_run();
    failures += test_linux_link_run();
    failures += test_linux_sync_run();
    failures += test_linux_utime_run();
    failures += test_linux_setid_run();
    failures += test_linux_chdir_run();
    failures += test_linux_xattr_run();
    failures += test_linux_statfs_run();
    failures += test_linux_advise_run();
    failures += test_linux_rlimit_legacy_run();
    failures += test_linux_caps_run();
    failures += test_linux_itimer_run();
    failures += test_linux_lock_run();
    failures += test_linux_sched_prio_run();
    failures += test_linux_posix_timer_run();
    failures += test_linux_time_legacy_run();
    failures += test_linux_sandbox_run();
    failures += test_linux_mincore_run();
    failures += test_linux_numa_run();
    failures += test_linux_settod_run();
    failures += test_linux_jit_aux_run();
    failures += test_linux_namespace_run();
    failures += test_linux_exec_ext_run();
    failures += test_linux_pipe_zero_run();
    failures += test_linux_proc_vm_run();
    failures += test_linux_openat2_run();
    failures += test_linux_pkey_run();
    failures += test_linux_landlock_run();
    failures += test_linux_seccomp_run();
    failures += test_linux_fanotify_run();
    failures += test_linux_io_uring_run();
    failures += test_linux_modern_misc_run();
    failures += test_stdin_buf_run();
    failures += test_gui_event_run();
    failures += test_compositor_events_run();
    failures += test_gui_window_dispatcher_run();
    failures += test_desktop_smoke_readiness_run();
    failures += test_dns_cache_run();
    failures += test_tls_hostname_run();
    failures += test_boot_slot_run();
    failures += run_op_budget_tests();
    failures += run_privilege_tests();
    failures += run_buffer_cache_pacing_tests();
    failures += test_syscall_pipe_priority_run();
    failures += test_syscall_net_run();
    failures += test_capylibc_net_run();
    failures += test_capylibc_tls_run();
    failures += test_syscall_net_init_run();
    failures += test_process_current_dynamic_run();

    if (failures == 0) {
        printf("Todos os testes passaram.\n");
        return 0;
    }
    printf("Falhas detectadas: %d\n", failures);
    return 1;
}
