#ifndef AUTH_LOGIN_RUNTIME_DISPLAY_BLIT_H
#define AUTH_LOGIN_RUNTIME_DISPLAY_BLIT_H

/*
 * include/auth/login_runtime/display_blit.h
 *
 * Internal partial header carrying the four display / output / blit /
 * framebuffer plan structs. These translate scanout work into the
 * actual display engine + DMA blit + framebuffer write pipeline.
 *
 *   - struct login_window_credential_screen_display_plan
 *   - struct login_window_credential_screen_output_plan
 *   - struct login_window_credential_screen_blit_plan
 *   - struct login_window_credential_screen_framebuffer_plan
 *
 * Standalone-includable: only primitives + const char* fields.
 * PR B+C+D #7b of the dedicated plan extracts unchanged byte-for-byte.
 */

#include <stddef.h>

struct login_window_credential_screen_display_plan {
  int version;
  int scanout_plan_available;
  int scanout_plan_safe;
  int display_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int display_credential_panel;
  int display_credential_input;
  int display_credential_focus;
  int display_text_recovery;
  int display_text_login;
  int display_text_login_resume;
  int display_text_login_fallback;
  int display_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_output_plan {
  int version;
  int display_plan_available;
  int display_plan_safe;
  int output_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int output_required;
  int output_allowed;
  int output_submitted;
  int output_ticket_selected;
  int output_target_selected;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int output_credential_panel;
  int output_credential_input;
  int output_credential_focus;
  int output_text_recovery;
  int output_text_login;
  int output_text_login_resume;
  int output_text_login_fallback;
  int output_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *output_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *output_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_blit_plan {
  int version;
  int output_plan_available;
  int output_plan_safe;
  int blit_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int output_required;
  int output_allowed;
  int output_submitted;
  int output_ticket_selected;
  int output_target_selected;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int blit_required;
  int blit_allowed;
  int blit_submitted;
  int blit_ticket_selected;
  int blit_target_selected;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int blit_credential_panel;
  int blit_credential_input;
  int blit_credential_focus;
  int blit_text_recovery;
  int blit_text_login;
  int blit_text_login_resume;
  int blit_text_login_fallback;
  int blit_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *output_ticket;
  const char *blit_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *output_policy;
  const char *blit_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_framebuffer_plan {
  int version;
  int blit_plan_available;
  int blit_plan_safe;
  int framebuffer_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int output_required;
  int output_allowed;
  int output_submitted;
  int output_ticket_selected;
  int output_target_selected;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int blit_required;
  int blit_allowed;
  int blit_submitted;
  int blit_ticket_selected;
  int blit_target_selected;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int framebuffer_required;
  int framebuffer_allowed;
  int framebuffer_submitted;
  int framebuffer_ticket_selected;
  int framebuffer_target_selected;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flush_required;
  int framebuffer_flushed;
  int framebuffer_cache_clean_required;
  int framebuffer_cache_cleaned;
  int framebuffer_credential_panel;
  int framebuffer_credential_input;
  int framebuffer_credential_focus;
  int framebuffer_text_recovery;
  int framebuffer_text_login;
  int framebuffer_text_login_resume;
  int framebuffer_text_login_fallback;
  int framebuffer_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *output_ticket;
  const char *blit_ticket;
  const char *framebuffer_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *output_policy;
  const char *blit_policy;
  const char *framebuffer_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

#endif /* AUTH_LOGIN_RUNTIME_DISPLAY_BLIT_H */
