#ifndef AUTH_LOGIN_RUNTIME_EXPIRY_PLAN_H
#define AUTH_LOGIN_RUNTIME_EXPIRY_PLAN_H

/*
 * include/auth/login_runtime/expiry_plan.h
 *
 * Standalone partial header for the
 *   struct login_window_credential_screen_expiry_plan
 * extracted byte-for-byte from `journal_retention.h` during PR 11d
 * (per-struct split to satisfy the 900-line audit rule). See
 * `docs/plans/active/monolith-residual-dedicated-plan.md`.
 */

#include <stddef.h>

struct login_window_credential_screen_expiry_plan {
  int version;
  int retention_plan_available;
  int retention_plan_safe;
  int expiry_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int receipt_required;
  int receipt_allowed;
  int receipt_submitted;
  int receipt_ticket_selected;
  int receipt_target_selected;
  int receipt_persist_allowed;
  int receipt_persisted;
  int receipt_cpu_gpu_sync_allowed;
  int receipt_cpu_gpu_sync_submitted;
  int ledger_required;
  int ledger_allowed;
  int ledger_submitted;
  int ledger_ticket_selected;
  int ledger_target_selected;
  int ledger_persist_allowed;
  int ledger_persisted;
  int ledger_cpu_gpu_sync_allowed;
  int ledger_cpu_gpu_sync_submitted;
  int journal_required;
  int journal_allowed;
  int journal_submitted;
  int journal_ticket_selected;
  int journal_target_selected;
  int journal_persist_allowed;
  int journal_persisted;
  int journal_cpu_gpu_sync_allowed;
  int journal_cpu_gpu_sync_submitted;
  int archive_required;
  int archive_allowed;
  int archive_submitted;
  int archive_ticket_selected;
  int archive_target_selected;
  int archive_persist_allowed;
  int archive_persisted;
  int archive_cpu_gpu_sync_allowed;
  int archive_cpu_gpu_sync_submitted;
  int retention_required;
  int retention_allowed;
  int retention_submitted;
  int retention_ticket_selected;
  int retention_target_selected;
  int retention_persist_allowed;
  int retention_persisted;
  int retention_cpu_gpu_sync_allowed;
  int retention_cpu_gpu_sync_submitted;
  int expiry_required;
  int expiry_allowed;
  int expiry_submitted;
  int expiry_ticket_selected;
  int expiry_target_selected;
  int expiry_persist_allowed;
  int expiry_persisted;
  int expiry_cpu_gpu_sync_allowed;
  int expiry_cpu_gpu_sync_submitted;
  int expiry_timer_allowed;
  int expiry_timer_armed;
  int expiry_delete_allowed;
  int expiry_deleted;
  int record_required;
  int record_allowed;
  int record_submitted;
  int record_ticket_selected;
  int record_target_selected;
  int record_persist_allowed;
  int record_persisted;
  int record_cpu_gpu_sync_allowed;
  int record_cpu_gpu_sync_submitted;
  int audit_required;
  int audit_allowed;
  int audit_submitted;
  int audit_ticket_selected;
  int audit_target_selected;
  int audit_log_append_allowed;
  int audit_log_appended;
  int audit_cpu_gpu_sync_allowed;
  int audit_cpu_gpu_sync_submitted;
  int seal_required;
  int seal_allowed;
  int seal_submitted;
  int seal_ticket_selected;
  int seal_target_selected;
  int seal_state_write_allowed;
  int seal_state_written;
  int seal_cpu_gpu_sync_allowed;
  int seal_cpu_gpu_sync_submitted;
  int cleanup_required;
  int cleanup_allowed;
  int cleanup_submitted;
  int cleanup_ticket_selected;
  int cleanup_target_selected;
  int cleanup_resource_release_allowed;
  int cleanup_resource_released;
  int cleanup_cpu_gpu_sync_allowed;
  int cleanup_cpu_gpu_sync_submitted;
  int retire_required;
  int retire_allowed;
  int retire_submitted;
  int retire_ticket_selected;
  int retire_target_selected;
  int retire_resource_release_allowed;
  int retire_resource_released;
  int retire_cpu_gpu_sync_allowed;
  int retire_cpu_gpu_sync_submitted;
  int ack_required;
  int ack_allowed;
  int ack_submitted;
  int ack_ticket_selected;
  int ack_target_selected;
  int ack_cpu_gpu_sync_allowed;
  int ack_cpu_gpu_sync_submitted;
  int completion_required;
  int completion_allowed;
  int completion_report_required;
  int completion_reported;
  int completion_ack_required;
  int completion_acknowledged;
  int completion_ticket_selected;
  int completion_target_selected;
  int completion_cpu_gpu_sync_allowed;
  int completion_cpu_gpu_sync_submitted;
  int deadline_required;
  int deadline_allowed;
  int deadline_armed;
  int deadline_timer_required;
  int deadline_timer_armed;
  int deadline_expired;
  int deadline_completion_required;
  int deadline_completion_reported;
  int deadline_cpu_gpu_sync_allowed;
  int deadline_cpu_gpu_sync_submitted;
  int sync_submitted;
  int sync_wait_allowed;
  int sync_wait_submitted;
  int sync_signal_allowed;
  int sync_signal_submitted;
  int sync_deadline_armed;
  int sync_completion_reported;
  int sync_cpu_gpu_sync_allowed;
  int sync_cpu_gpu_sync_submitted;
  int timeline_submitted;
  int timeline_wait_allowed;
  int timeline_wait_submitted;
  int timeline_signal_allowed;
  int timeline_signal_submitted;
  int timeline_semaphore_allowed;
  int timeline_semaphore_submitted;
  int timeline_value_allocated;
  int timeline_value_published;
  int timeline_cpu_gpu_sync_allowed;
  int timeline_cpu_gpu_sync_submitted;
  int fence_submitted;
  int fence_wait_allowed;
  int fence_wait_submitted;
  int fence_signal_allowed;
  int fence_signal_submitted;
  int fence_fd_export_allowed;
  int fence_fd_exported;
  int fence_cpu_gpu_sync_allowed;
  int fence_cpu_gpu_sync_submitted;
  int barrier_submitted;
  int barrier_memory_visibility_established;
  int barrier_cache_visibility_established;
  int barrier_cpu_gpu_sync_allowed;
  int barrier_cpu_gpu_sync_submitted;
  int flush_submitted;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int framebuffer_submitted;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flushed;
  int framebuffer_cache_cleaned;
  int blit_submitted;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int output_submitted;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int display_submitted;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int scanout_submitted;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int vsync_submitted;
  int vsync_wait_submitted;
  int vsync_fence_armed;
  int schedule_submitted;
  int present_submitted;
  int damage_submitted;
  int compositor_damage_submitted;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int record_credential_panel;
  int record_credential_input;
  int record_credential_focus;
  int record_text_recovery;
  int record_text_login;
  int record_text_login_resume;
  int record_text_login_fallback;
  int record_error;
  int receipt_credential_panel;
  int receipt_credential_input;
  int receipt_credential_focus;
  int receipt_text_recovery;
  int receipt_text_login;
  int receipt_text_login_resume;
  int receipt_text_login_fallback;
  int receipt_error;
  int ledger_credential_panel;
  int ledger_credential_input;
  int ledger_credential_focus;
  int ledger_text_recovery;
  int ledger_text_login;
  int ledger_text_login_resume;
  int ledger_text_login_fallback;
  int ledger_error;
  int journal_credential_panel;
  int journal_credential_input;
  int journal_credential_focus;
  int journal_text_recovery;
  int journal_text_login;
  int journal_text_login_resume;
  int journal_text_login_fallback;
  int journal_error;
  int archive_credential_panel;
  int archive_credential_input;
  int archive_credential_focus;
  int archive_text_recovery;
  int archive_text_login;
  int archive_text_login_resume;
  int archive_text_login_fallback;
  int archive_error;
  int retention_credential_panel;
  int retention_credential_input;
  int retention_credential_focus;
  int retention_text_recovery;
  int retention_text_login;
  int retention_text_login_resume;
  int retention_text_login_fallback;
  int retention_error;
  int expiry_credential_panel;
  int expiry_credential_input;
  int expiry_credential_focus;
  int expiry_text_recovery;
  int expiry_text_login;
  int expiry_text_login_resume;
  int expiry_text_login_fallback;
  int expiry_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *record_ticket;
  const char *receipt_ticket;
  const char *ledger_ticket;
  const char *journal_ticket;
  const char *archive_ticket;
  const char *retention_ticket;
  const char *expiry_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *record_policy;
  const char *receipt_policy;
  const char *ledger_policy;
  const char *journal_policy;
  const char *archive_policy;
  const char *retention_policy;
  const char *expiry_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

#endif /* AUTH_LOGIN_RUNTIME_EXPIRY_PLAN_H */
