#ifndef AUTH_LOGIN_RUNTIME_FLUSH_SYNC_H
#define AUTH_LOGIN_RUNTIME_FLUSH_SYNC_H

/*
 * include/auth/login_runtime/flush_sync.h
 *
 * Internal partial header carrying the five flush / barrier / fence /
 * timeline / sync plan structs. These translate framebuffer work
 * into cache-coherent visibility guarantees and CPU/GPU
 * synchronization primitives.
 *
 *   - struct login_window_credential_screen_flush_plan
 *   - struct login_window_credential_screen_barrier_plan
 *   - struct login_window_credential_screen_fence_plan
 *   - struct login_window_credential_screen_timeline_plan
 *   - struct login_window_credential_screen_sync_plan
 *
 * Standalone-includable: only primitives + const char* fields.
 * PR B+C+D #7c of the dedicated plan extracts unchanged byte-for-byte.
 */

#include <stddef.h>

struct login_window_credential_screen_flush_plan {
  int version;
  int framebuffer_plan_available;
  int framebuffer_plan_safe;
  int flush_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int output_required;
  int output_allowed;
  int output_submitted;
  int output_ticket_selected;
  int output_target_selected;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int blit_required;
  int blit_allowed;
  int blit_submitted;
  int blit_ticket_selected;
  int blit_target_selected;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int framebuffer_required;
  int framebuffer_allowed;
  int framebuffer_submitted;
  int framebuffer_ticket_selected;
  int framebuffer_target_selected;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flush_required;
  int framebuffer_flushed;
  int framebuffer_cache_clean_required;
  int framebuffer_cache_cleaned;
  int flush_required;
  int flush_allowed;
  int flush_submitted;
  int flush_ticket_selected;
  int flush_target_selected;
  int flush_cache_clean_required;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int flush_credential_panel;
  int flush_credential_input;
  int flush_credential_focus;
  int flush_text_recovery;
  int flush_text_login;
  int flush_text_login_resume;
  int flush_text_login_fallback;
  int flush_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *output_ticket;
  const char *blit_ticket;
  const char *framebuffer_ticket;
  const char *flush_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *output_policy;
  const char *blit_policy;
  const char *framebuffer_policy;
  const char *flush_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_barrier_plan {
  int version;
  int flush_plan_available;
  int flush_plan_safe;
  int barrier_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int flush_allowed;
  int flush_submitted;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int framebuffer_submitted;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flushed;
  int framebuffer_cache_cleaned;
  int blit_submitted;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int output_submitted;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int display_submitted;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int scanout_submitted;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int vsync_submitted;
  int vsync_wait_submitted;
  int vsync_fence_armed;
  int schedule_submitted;
  int present_submitted;
  int damage_submitted;
  int compositor_damage_submitted;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int barrier_required;
  int barrier_allowed;
  int barrier_submitted;
  int barrier_ticket_selected;
  int barrier_target_selected;
  int barrier_memory_visibility_required;
  int barrier_memory_visibility_established;
  int barrier_cache_visibility_required;
  int barrier_cache_visibility_established;
  int barrier_cpu_gpu_sync_allowed;
  int barrier_cpu_gpu_sync_submitted;
  int barrier_credential_panel;
  int barrier_credential_input;
  int barrier_credential_focus;
  int barrier_text_recovery;
  int barrier_text_login;
  int barrier_text_login_resume;
  int barrier_text_login_fallback;
  int barrier_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *flush_ticket;
  const char *barrier_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *flush_policy;
  const char *barrier_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_fence_plan {
  int version;
  int barrier_plan_available;
  int barrier_plan_safe;
  int fence_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int barrier_allowed;
  int barrier_submitted;
  int barrier_memory_visibility_established;
  int barrier_cache_visibility_established;
  int barrier_cpu_gpu_sync_allowed;
  int barrier_cpu_gpu_sync_submitted;
  int flush_submitted;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int framebuffer_submitted;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flushed;
  int framebuffer_cache_cleaned;
  int blit_submitted;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int output_submitted;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int display_submitted;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int scanout_submitted;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int vsync_submitted;
  int vsync_wait_submitted;
  int vsync_fence_armed;
  int schedule_submitted;
  int present_submitted;
  int damage_submitted;
  int compositor_damage_submitted;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int fence_required;
  int fence_allowed;
  int fence_submitted;
  int fence_ticket_selected;
  int fence_target_selected;
  int fence_wait_required;
  int fence_wait_allowed;
  int fence_wait_submitted;
  int fence_signal_allowed;
  int fence_signal_submitted;
  int fence_fd_export_allowed;
  int fence_fd_exported;
  int fence_cpu_gpu_sync_allowed;
  int fence_cpu_gpu_sync_submitted;
  int fence_credential_panel;
  int fence_credential_input;
  int fence_credential_focus;
  int fence_text_recovery;
  int fence_text_login;
  int fence_text_login_resume;
  int fence_text_login_fallback;
  int fence_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *barrier_ticket;
  const char *fence_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *barrier_policy;
  const char *fence_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_timeline_plan {
  int version;
  int fence_plan_available;
  int fence_plan_safe;
  int timeline_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int fence_allowed;
  int fence_submitted;
  int fence_wait_allowed;
  int fence_wait_submitted;
  int fence_signal_allowed;
  int fence_signal_submitted;
  int fence_fd_export_allowed;
  int fence_fd_exported;
  int fence_cpu_gpu_sync_allowed;
  int fence_cpu_gpu_sync_submitted;
  int barrier_submitted;
  int barrier_memory_visibility_established;
  int barrier_cache_visibility_established;
  int barrier_cpu_gpu_sync_allowed;
  int barrier_cpu_gpu_sync_submitted;
  int flush_submitted;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int framebuffer_submitted;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flushed;
  int framebuffer_cache_cleaned;
  int blit_submitted;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int output_submitted;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int display_submitted;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int scanout_submitted;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int vsync_submitted;
  int vsync_wait_submitted;
  int vsync_fence_armed;
  int schedule_submitted;
  int present_submitted;
  int damage_submitted;
  int compositor_damage_submitted;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int timeline_required;
  int timeline_allowed;
  int timeline_submitted;
  int timeline_ticket_selected;
  int timeline_target_selected;
  int timeline_wait_required;
  int timeline_wait_allowed;
  int timeline_wait_submitted;
  int timeline_signal_allowed;
  int timeline_signal_submitted;
  int timeline_semaphore_allowed;
  int timeline_semaphore_submitted;
  int timeline_value_required;
  int timeline_value_allocated;
  int timeline_value_published;
  int timeline_cpu_gpu_sync_allowed;
  int timeline_cpu_gpu_sync_submitted;
  int timeline_credential_panel;
  int timeline_credential_input;
  int timeline_credential_focus;
  int timeline_text_recovery;
  int timeline_text_login;
  int timeline_text_login_resume;
  int timeline_text_login_fallback;
  int timeline_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *fence_ticket;
  const char *timeline_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *fence_policy;
  const char *timeline_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_sync_plan {
  int version;
  int timeline_plan_available;
  int timeline_plan_safe;
  int sync_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int timeline_allowed;
  int timeline_submitted;
  int timeline_wait_allowed;
  int timeline_wait_submitted;
  int timeline_signal_allowed;
  int timeline_signal_submitted;
  int timeline_semaphore_allowed;
  int timeline_semaphore_submitted;
  int timeline_value_allocated;
  int timeline_value_published;
  int timeline_cpu_gpu_sync_allowed;
  int timeline_cpu_gpu_sync_submitted;
  int fence_submitted;
  int fence_wait_allowed;
  int fence_wait_submitted;
  int fence_signal_allowed;
  int fence_signal_submitted;
  int fence_fd_export_allowed;
  int fence_fd_exported;
  int fence_cpu_gpu_sync_allowed;
  int fence_cpu_gpu_sync_submitted;
  int barrier_submitted;
  int barrier_memory_visibility_established;
  int barrier_cache_visibility_established;
  int barrier_cpu_gpu_sync_allowed;
  int barrier_cpu_gpu_sync_submitted;
  int flush_submitted;
  int flush_cache_clean_allowed;
  int flush_cache_cleaned;
  int flush_memory_barrier_allowed;
  int flush_memory_barrier_submitted;
  int framebuffer_submitted;
  int framebuffer_mapped;
  int framebuffer_write_allowed;
  int framebuffer_written;
  int framebuffer_flushed;
  int framebuffer_cache_cleaned;
  int blit_submitted;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int output_submitted;
  int output_buffer_attached;
  int output_buffer_submitted;
  int output_flip_allowed;
  int output_flip_submitted;
  int display_submitted;
  int display_buffer_attached;
  int display_buffer_submitted;
  int display_mode_committed;
  int display_flip_allowed;
  int display_flip_submitted;
  int scanout_submitted;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int vsync_submitted;
  int vsync_wait_submitted;
  int vsync_fence_armed;
  int schedule_submitted;
  int present_submitted;
  int damage_submitted;
  int compositor_damage_submitted;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int sync_required;
  int sync_allowed;
  int sync_submitted;
  int sync_ticket_selected;
  int sync_target_selected;
  int sync_wait_required;
  int sync_wait_allowed;
  int sync_wait_submitted;
  int sync_signal_allowed;
  int sync_signal_submitted;
  int sync_deadline_required;
  int sync_deadline_armed;
  int sync_completion_required;
  int sync_completion_reported;
  int sync_cpu_gpu_sync_allowed;
  int sync_cpu_gpu_sync_submitted;
  int sync_credential_panel;
  int sync_credential_input;
  int sync_credential_focus;
  int sync_text_recovery;
  int sync_text_login;
  int sync_text_login_resume;
  int sync_text_login_fallback;
  int sync_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *timeline_ticket;
  const char *sync_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *timeline_policy;
  const char *sync_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

#endif /* AUTH_LOGIN_RUNTIME_FLUSH_SYNC_H */
