#ifndef AUTH_LOGIN_RUNTIME_PRESENT_SCANOUT_H
#define AUTH_LOGIN_RUNTIME_PRESENT_SCANOUT_H

/*
 * include/auth/login_runtime/present_scanout.h
 *
 * Internal partial header carrying the four present / schedule /
 * vsync / scanout plan structs. These compose the compositor output
 * pipeline that turns damage plans into pixel scan-out work.
 *
 *   - struct login_window_credential_screen_present_plan
 *   - struct login_window_credential_screen_schedule_plan
 *   - struct login_window_credential_screen_vsync_plan
 *   - struct login_window_credential_screen_scanout_plan
 *
 * Standalone-includable: only primitives + const char* fields.
 * PR B+C+D #7 of the dedicated plan extracts unchanged byte-for-byte.
 */

#include <stddef.h>

struct login_window_credential_screen_present_plan {
  int version;
  int damage_plan_available;
  int damage_plan_safe;
  int present_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int present_credential_panel;
  int present_credential_input;
  int present_credential_focus;
  int present_text_recovery;
  int present_text_login;
  int present_text_login_resume;
  int present_text_login_fallback;
  int present_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_schedule_plan {
  int version;
  int present_plan_available;
  int present_plan_safe;
  int schedule_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int schedule_credential_panel;
  int schedule_credential_input;
  int schedule_credential_focus;
  int schedule_text_recovery;
  int schedule_text_login;
  int schedule_text_login_resume;
  int schedule_text_login_fallback;
  int schedule_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_vsync_plan {
  int version;
  int schedule_plan_available;
  int schedule_plan_safe;
  int vsync_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int vsync_credential_panel;
  int vsync_credential_input;
  int vsync_credential_focus;
  int vsync_text_recovery;
  int vsync_text_login;
  int vsync_text_login_resume;
  int vsync_text_login_fallback;
  int vsync_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

struct login_window_credential_screen_scanout_plan {
  int version;
  int vsync_plan_available;
  int vsync_plan_safe;
  int scanout_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int display_mode_required;
  int display_mode_committed;
  int scanout_credential_panel;
  int scanout_credential_input;
  int scanout_credential_focus;
  int scanout_text_recovery;
  int scanout_text_login;
  int scanout_text_login_resume;
  int scanout_text_login_fallback;
  int scanout_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

#endif /* AUTH_LOGIN_RUNTIME_PRESENT_SCANOUT_H */
