#ifndef AUTH_LOGIN_RUNTIME_WINDOW_BLIT_PLAN_H
#define AUTH_LOGIN_RUNTIME_WINDOW_BLIT_PLAN_H

/*
 * include/auth/login_runtime/window_blit_plan.h
 *
 * Standalone partial header for the
 *   struct login_window_credential_screen_window_blit_plan
 * extracted byte-for-byte from `window_output.h` during PR 11e
 * (per-struct split to satisfy the 900-line audit rule). See
 * `docs/plans/active/monolith-residual-dedicated-plan.md`.
 */

#include <stddef.h>

struct login_window_credential_screen_window_blit_plan {
  int version;
  int window_output_plan_available;
  int window_display_plan_available;
  int window_scanout_plan_available;
  int window_vsync_plan_available;
  int window_schedule_plan_available;
  int window_present_plan_available;
  int window_damage_plan_available;
  int window_compositor_plan_available;
  int window_surface_plan_available;
  int window_surface_plan_safe;
  int window_compositor_plan_safe;
  int window_damage_plan_safe;
  int window_present_plan_safe;
  int window_schedule_plan_safe;
  int window_vsync_plan_safe;
  int window_scanout_plan_safe;
  int window_display_plan_safe;
  int window_output_plan_safe;
  int window_blit_plan_safe;
  int requested_action;
  int route_selected;
  int route_blocked;
  int action_allowed;
  int action_blocked;
  int input_focus_allowed;
  int compaction_required;
  int compaction_allowed;
  int compaction_submitted;
  int compaction_ticket_selected;
  int compaction_target_selected;
  int reclaim_required;
  int reclaim_allowed;
  int reclaim_submitted;
  int reclaim_ticket_selected;
  int reclaim_target_selected;
  int release_required;
  int release_allowed;
  int release_submitted;
  int release_ticket_selected;
  int release_target_selected;
  int gui_required;
  int gui_allowed;
  int gui_submitted;
  int gui_ticket_selected;
  int gui_target_selected;
  int window_required;
  int window_allowed;
  int window_created;
  int window_ticket_selected;
  int window_target_selected;
  int window_surface_bound;
  int window_input_bound;
  int surface_required;
  int surface_allowed;
  int surface_bound;
  int surface_ticket_selected;
  int surface_target_selected;
  int surface_memory_mapped;
  int surface_pixels_written;
  int compositor_required;
  int compositor_allowed;
  int compositor_submitted;
  int compositor_ticket_selected;
  int compositor_target_selected;
  int compositor_surface_allowed;
  int compositor_surface_submitted;
  int compositor_damage_planned;
  int compositor_damage_allowed;
  int compositor_damage_submitted;
  int damage_required;
  int damage_allowed;
  int damage_submitted;
  int damage_ticket_selected;
  int damage_target_selected;
  int damage_incremental_allowed;
  int full_damage_required;
  int damage_cache_allowed;
  int damage_cache_hit;
  int damage_reuse_allowed;
  int damage_error;
  int present_required;
  int present_allowed;
  int present_submitted;
  int present_ticket_selected;
  int present_target_selected;
  int present_incremental_allowed;
  int full_present_required;
  int present_cache_allowed;
  int present_cache_hit;
  int present_reuse_allowed;
  int present_error;
  int schedule_required;
  int schedule_allowed;
  int schedule_submitted;
  int schedule_ticket_selected;
  int schedule_target_selected;
  int schedule_incremental_allowed;
  int full_schedule_required;
  int schedule_cache_allowed;
  int schedule_cache_hit;
  int schedule_reuse_allowed;
  int frame_pacing_required;
  int frame_pacing_allowed;
  int frame_timer_armed;
  int compositor_wake_allowed;
  int compositor_wake_submitted;
  int page_flip_allowed;
  int page_flip_submitted;
  int schedule_error;
  int vsync_required;
  int vsync_allowed;
  int vsync_submitted;
  int vsync_ticket_selected;
  int vsync_target_selected;
  int vsync_wait_allowed;
  int vsync_wait_submitted;
  int vsync_fence_required;
  int vsync_fence_armed;
  int vsync_error;
  int scanout_required;
  int scanout_allowed;
  int scanout_submitted;
  int scanout_ticket_selected;
  int scanout_target_selected;
  int scanout_buffer_attached;
  int scanout_buffer_submitted;
  int scanout_display_flip_allowed;
  int scanout_display_flip_submitted;
  int scanout_error;
  int display_required;
  int display_allowed;
  int display_submitted;
  int display_ticket_selected;
  int display_target_selected;
  int display_controller_attached;
  int display_controller_submitted;
  int display_output_attached;
  int display_output_submitted;
  int display_pipeline_attached;
  int display_pipeline_submitted;
  int display_error;
  int output_required;
  int output_allowed;
  int output_submitted;
  int output_ticket_selected;
  int output_target_selected;
  int output_connector_attached;
  int output_connector_submitted;
  int output_mode_attached;
  int output_mode_submitted;
  int output_signal_armed;
  int output_signal_submitted;
  int output_error;
  int blit_required;
  int blit_allowed;
  int blit_submitted;
  int blit_ticket_selected;
  int blit_target_selected;
  int blit_source_buffer_mapped;
  int blit_destination_buffer_mapped;
  int blit_pixels_copied;
  int blit_dma_allowed;
  int blit_dma_submitted;
  int blit_credential_panel;
  int blit_credential_input;
  int blit_credential_focus;
  int blit_text_recovery;
  int blit_text_login;
  int blit_text_login_resume;
  int blit_text_login_fallback;
  int blit_error;
  int submit_callback_bound;
  int auth_callback_bound;
  int recovery_text_session_required;
  int session_reset_required;
  int login_screen_rerender_required;
  int credential_session_safe;
  int credential_storage_wiped;
  int credential_redacted;
  int length_redacted;
  int raw_secret_exposed;
  int masked_text_exposed;
  int submit_requested;
  int submit_blocked;
  int submit_enabled;
  int auth_attempt_allowed;
  int text_login_authoritative;
  const char *view;
  const char *widget_tree;
  const char *compaction_ticket;
  const char *reclaim_ticket;
  const char *release_ticket;
  const char *gui_ticket;
  const char *window_ticket;
  const char *surface_ticket;
  const char *compositor_ticket;
  const char *damage_ticket;
  const char *present_ticket;
  const char *schedule_ticket;
  const char *vsync_ticket;
  const char *scanout_ticket;
  const char *display_ticket;
  const char *output_ticket;
  const char *blit_ticket;
  const char *focus_target;
  const char *primary_action;
  const char *route;
  const char *compositor_target;
  const char *compaction_policy;
  const char *reclaim_policy;
  const char *release_policy;
  const char *gui_policy;
  const char *window_policy;
  const char *surface_policy;
  const char *compositor_policy;
  const char *damage_policy;
  const char *cache_policy;
  const char *present_policy;
  const char *schedule_policy;
  const char *vsync_policy;
  const char *scanout_policy;
  const char *display_policy;
  const char *output_policy;
  const char *blit_policy;
  const char *event_type;
  const char *state;
  const char *message;
  const char *blocked_reason;
};

#endif /* AUTH_LOGIN_RUNTIME_WINDOW_BLIT_PLAN_H */
