#include "grub_cfg_builder.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct buffer {
  char *out;
  size_t size;
  size_t len;
};

static void buffer_reset(struct buffer *buf) {
  if (!buf || !buf->out || buf->size == 0) {
    return;
  }
  buf->len = 0;
  buf->out[0] = '\0';
}

static int buffer_append(struct buffer *buf, const char *text) {
  if (!buf || !buf->out || buf->size == 0 || !text) {
    return -1;
  }
  size_t to_copy = strlen(text);
  if (to_copy == 0) {
    return 0;
  }
  if (buf->len + to_copy >= buf->size) {
    return -1;
  }
  memcpy(buf->out + buf->len, text, to_copy);
  buf->len += to_copy;
  buf->out[buf->len] = '\0';
  return 0;
}

static int buffer_append_line(struct buffer *buf, const char *text) {
  if (buffer_append(buf, text) != 0) {
    return -1;
  }
  if (buffer_append(buf, "\n") != 0) {
    return -1;
  }
  return 0;
}

static int buffer_append_line_fmt(struct buffer *buf, const char *fmt, ...) {
  if (!buf || !fmt) {
    return -1;
  }
  char line[512];
  va_list ap;
  va_start(ap, fmt);
  int written = vsnprintf(line, sizeof(line), fmt, ap);
  va_end(ap);
  if (written < 0 || (size_t)written >= sizeof(line)) {
    return -1; // formato excedeu o buffer temporario
  }
  return buffer_append_line(buf, line);
}

static int append_terminal_lines(struct buffer *buf,
                                 const struct grub_cfg_options *opts) {
  if (!opts) {
    return -1;
  }
  if (opts->enable_serial) {
    unsigned int baud = opts->serial_baud ? opts->serial_baud : 115200;
    if (buffer_append_line_fmt(
            buf, "serial --unit=0 --speed=%u --word=8 --parity=no --stop=1",
            baud) != 0) {
      return -1;
    }
  }
  if (buffer_append_line_fmt(buf, "terminal_input console%s",
                             opts->enable_serial ? " serial" : "") != 0) {
    return -1;
  }
  if (buffer_append_line_fmt(buf, "terminal_output console%s",
                             opts->enable_serial ? " serial" : "") != 0) {
    return -1;
  }
  return 0;
}

int grub_cfg_build(const struct grub_cfg_options *opts,
                   const struct grub_menu_entry *entries, size_t entry_count,
                   char *out, size_t out_size) {
  if (!opts || !entries || entry_count == 0 || !out || out_size < 2) {
    return -1;
  }
  if (opts->timeout_seconds < 0 || opts->default_entry < 0) {
    return -1;
  }
  if ((size_t)opts->default_entry >= entry_count) {
    return -1;
  }

  struct buffer buf = {out, out_size, 0};
  buffer_reset(&buf);

  if (buffer_append_line(
          &buf,
          "# Auto-generated grub.cfg (text console enforced for Hyper-V)") !=
      0) {
    return -1;
  }
  if (buffer_append_line(&buf, "# Do not edit this file manually; regenerate "
                               "via tools/gen_grub_cfg") != 0) {
    return -1;
  }
  if (buffer_append_line_fmt(&buf, "set timeout=%d", opts->timeout_seconds) !=
      0) {
    return -1;
  }
  if (buffer_append_line_fmt(&buf, "set default=%d", opts->default_entry) !=
      0) {
    return -1;
  }
  if (opts->force_text_mode) {
    if (buffer_append_line(&buf, "set gfxpayload=text") != 0) {
      return -1;
    }
  }
  if (buffer_append_line(&buf, "") != 0) {
    return -1;
  }
  if (append_terminal_lines(&buf, opts) != 0) {
    return -1;
  }
  if (buffer_append_line(&buf, "") != 0) {
    return -1;
  }

  for (size_t i = 0; i < entry_count; ++i) {
    if (!entries[i].title || !entries[i].multiboot_path) {
      return -1;
    }
    if (buffer_append_line_fmt(&buf, "menuentry \"%s\" {", entries[i].title) !=
        0) {
      return -1;
    }
    if (buffer_append_line_fmt(&buf, "    multiboot %s",
                               entries[i].multiboot_path) != 0) {
      return -1;
    }
    if (buffer_append_line(&buf, "    boot") != 0) {
      return -1;
    }
    if (buffer_append_line(&buf, "}") != 0) {
      return -1;
    }
    if (buffer_append_line(&buf, "") != 0) {
      return -1;
    }
  }

  return 0;
}

int grub_cfg_write_file(const char *path, const struct grub_cfg_options *opts,
                        const struct grub_menu_entry *entries,
                        size_t entry_count) {
  if (!path) {
    return -1;
  }

  // Buffer generoso para 2-3 entradas com comentários e blocos.
  size_t buffer_size = 4096;
  char *buffer = (char *)malloc(buffer_size);
  if (!buffer) {
    return -1;
  }

  int rc = grub_cfg_build(opts, entries, entry_count, buffer, buffer_size);
  if (rc != 0) {
    free(buffer);
    return -1;
  }

  FILE *f = fopen(path, "w");
  if (!f) {
    free(buffer);
    return -1;
  }
  size_t expected = strlen(buffer);
  size_t written = fwrite(buffer, 1, expected, f);
  fclose(f);
  free(buffer);
  return written == expected ? 0 : -1;
}
