#include "security/chacha20_poly1305.h"
#include "security/crypt.h"
#include <stddef.h>
#include <stdint.h>

/*
 * ChaCha20-Poly1305 AEAD (RFC 8439).
 *
 * Tres primitivas implementadas neste arquivo:
 *  1. ChaCha20 block function (§2.3): 20-round permutation produzindo
 *     64 bytes de keystream por (key, counter, nonce).
 *  2. ChaCha20 stream cipher (§2.4): XOR de plaintext com keystream
 *     generated by ChaCha20 block iterado sobre counter.
 *  3. Poly1305 one-time MAC (§2.5): polinomio sobre GF(2^130-5) com
 *     chave clamped + offset s.
 *  4. AEAD construction (§2.8): combina ChaCha20-encrypt com
 *     Poly1305-mac sobre (aad || ct || lens) e usa OTK derivada
 *     do bloco 0 da ChaCha20.
 *
 * Sao agrupadas em um unico arquivo porque (a) sao a familia
 * canonica que so faz sentido junta (ChaCha20 isolado e raramente
 * util; Poly1305 com chave reutilizada e quebrado) e (b) a
 * orquestracao AEAD precisa de acesso direto as primitivas para a
 * derivacao de OTK do bloco 0.
 */

/* ============================================================
 * Helpers de endianness (little-endian per RFC).
 * ============================================================ */

static inline uint32_t load32_le(const uint8_t *p) {
  return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
         ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

static inline void store32_le(uint8_t *p, uint32_t v) {
  p[0] = (uint8_t)(v & 0xFFu);
  p[1] = (uint8_t)((v >> 8) & 0xFFu);
  p[2] = (uint8_t)((v >> 16) & 0xFFu);
  p[3] = (uint8_t)((v >> 24) & 0xFFu);
}

static inline void store64_le(uint8_t *p, uint64_t v) {
  for (int i = 0; i < 8; ++i) {
    p[i] = (uint8_t)((v >> (8 * i)) & 0xFFu);
  }
}

static inline uint32_t rotl32(uint32_t v, int n) {
  return (v << n) | (v >> (32 - n));
}

/*
 * Wipe volatile-safe contra dead-store elimination. Compositionalmente
 * espelha o pattern de `memory_zero` em outros sites cripto do
 * projeto; usamos local aqui em vez de depender de header externo
 * para manter este modulo audit-self-contained.
 */
static void wipe(void *p, size_t n) {
  volatile uint8_t *vp = (volatile uint8_t *)p;
  while (n--) {
    *vp++ = 0u;
  }
}

/* ============================================================
 * ChaCha20 (RFC 8439 §2.1-2.4).
 * ============================================================ */

/* Constantes "expand 32-byte k" little-endian. */
static const uint32_t k_chacha20_constants[4] = {
    0x61707865u, 0x3320646eu, 0x79622d32u, 0x6b206574u};

/*
 * Quarter round (RFC 8439 §2.1). Quatro ARX operations sobre 4 words
 * do state. Implementada como macro para forcar inlining e evitar
 * overhead de funcao em hot path.
 */
#define QR(a, b, c, d)                                                         \
  do {                                                                         \
    a += b;                                                                    \
    d ^= a;                                                                    \
    d = rotl32(d, 16);                                                         \
    c += d;                                                                    \
    b ^= c;                                                                    \
    b = rotl32(b, 12);                                                         \
    a += b;                                                                    \
    d ^= a;                                                                    \
    d = rotl32(d, 8);                                                          \
    c += d;                                                                    \
    b ^= c;                                                                    \
    b = rotl32(b, 7);                                                          \
  } while (0)

/*
 * 20-round ChaCha20 block function. 10 column rounds + 10 diagonal
 * rounds = 20 rounds total (alternados). Output e state + state_inicial
 * (Feistel-like avalanche back-add).
 */
static void chacha20_block_inner(const uint32_t state_in[16],
                                 uint32_t state_out[16]) {
  uint32_t s[16];
  for (int i = 0; i < 16; ++i) {
    s[i] = state_in[i];
  }
  for (int round = 0; round < 10; ++round) {
    /* Column rounds. */
    QR(s[0], s[4], s[8], s[12]);
    QR(s[1], s[5], s[9], s[13]);
    QR(s[2], s[6], s[10], s[14]);
    QR(s[3], s[7], s[11], s[15]);
    /* Diagonal rounds. */
    QR(s[0], s[5], s[10], s[15]);
    QR(s[1], s[6], s[11], s[12]);
    QR(s[2], s[7], s[8], s[13]);
    QR(s[3], s[4], s[9], s[14]);
  }
  for (int i = 0; i < 16; ++i) {
    state_out[i] = s[i] + state_in[i];
  }
  wipe(s, sizeof(s));
}

int chacha20_block(const uint8_t key[CHACHA20_KEY_SIZE], uint32_t counter,
                   const uint8_t nonce[CHACHA20_NONCE_SIZE],
                   uint8_t out[CHACHA20_BLOCK_SIZE]) {
  if (!key || !nonce || !out) {
    return -1;
  }
  uint32_t state_in[16];
  uint32_t state_out[16];
  state_in[0] = k_chacha20_constants[0];
  state_in[1] = k_chacha20_constants[1];
  state_in[2] = k_chacha20_constants[2];
  state_in[3] = k_chacha20_constants[3];
  for (int i = 0; i < 8; ++i) {
    state_in[4 + i] = load32_le(key + 4 * i);
  }
  state_in[12] = counter;
  state_in[13] = load32_le(nonce + 0);
  state_in[14] = load32_le(nonce + 4);
  state_in[15] = load32_le(nonce + 8);

  chacha20_block_inner(state_in, state_out);

  for (int i = 0; i < 16; ++i) {
    store32_le(out + 4 * i, state_out[i]);
  }
  wipe(state_in, sizeof(state_in));
  wipe(state_out, sizeof(state_out));
  return 0;
}

int chacha20_encrypt(const uint8_t key[CHACHA20_KEY_SIZE],
                     uint32_t initial_counter,
                     const uint8_t nonce[CHACHA20_NONCE_SIZE],
                     const uint8_t *in, uint8_t *out, size_t len) {
  if (len == 0u) {
    /* Vacuously successful. NULL in/out tolerado quando len==0. */
    return (key && nonce) ? 0 : -1;
  }
  if (!key || !nonce || !in || !out) {
    return -1;
  }
  /* Counter overflow protection. Numero de blocos necessarios =
   * ceil(len/64). Se initial_counter + n_blocks > 2^32, o counter
   * enrolaria e reciclaria keystream blocks ja emitidos para a mesma
   * (key, nonce) — vetor catastrofico de keystream recovery via XOR.
   * Rejeita fail-closed. */
  uint64_t n_blocks = ((uint64_t)len + 63u) / 64u;
  if ((uint64_t)initial_counter + n_blocks > (uint64_t)0xFFFFFFFFull + 1ull) {
    return -1;
  }

  uint8_t keystream[CHACHA20_BLOCK_SIZE];
  size_t off = 0u;
  uint32_t counter = initial_counter;
  while (off < len) {
    if (chacha20_block(key, counter, nonce, keystream) != 0) {
      wipe(keystream, sizeof(keystream));
      return -1;
    }
    size_t chunk = len - off;
    if (chunk > CHACHA20_BLOCK_SIZE) {
      chunk = CHACHA20_BLOCK_SIZE;
    }
    for (size_t i = 0u; i < chunk; ++i) {
      out[off + i] = in[off + i] ^ keystream[i];
    }
    off += chunk;
    counter += 1u;
  }
  wipe(keystream, sizeof(keystream));
  return 0;
}

/* ============================================================
 * Poly1305 (RFC 8439 §2.5).
 *
 * Implementacao em radix-26 (5 limbs de 26 bits cada) sobre 32-bit
 * arithmetic. Aceita 16-byte blocks, padding com 1-byte 0x01 ao final
 * de cada bloco completo, e bloco final com tamanho < 16 ganhando
 * append explicito de byte 0x01 antes do padding zero.
 *
 * O modulo de operacao e 2^130-5. A multiplicacao a*r reduzida e
 * feita em 64-bit accumulators, com reducao via "*5 + carry" (a tecnica
 * padrao para 2^130-5 = 5*2^130).
 * ============================================================ */

struct poly1305_state {
  uint32_t r[5];   /* Clamped key (low 16 bytes). */
  uint32_t h[5];   /* Accumulator. */
  uint32_t s[4];   /* Pad (high 16 bytes), used in finalize. */
  uint8_t buffer[16];
  size_t buffer_used;
};

static void poly1305_init(struct poly1305_state *st,
                          const uint8_t key[POLY1305_KEY_SIZE]) {
  /* RFC 8439 §2.5: clamp r per the bit-mask
   * 0x0ffffffc0ffffffc0ffffffc0fffffff (little-endian byte order). */
  uint32_t r0 = load32_le(key + 0) & 0x0FFFFFFFu;
  uint32_t r1 = load32_le(key + 4) & 0x0FFFFFFCu;
  uint32_t r2 = load32_le(key + 8) & 0x0FFFFFFCu;
  uint32_t r3 = load32_le(key + 12) & 0x0FFFFFFCu;
  /* Quebra r de 128 bits em 5 limbs de 26 bits cada. */
  st->r[0] = r0 & 0x3FFFFFFu;
  st->r[1] = ((r0 >> 26) | (r1 << 6)) & 0x3FFFFFFu;
  st->r[2] = ((r1 >> 20) | (r2 << 12)) & 0x3FFFFFFu;
  st->r[3] = ((r2 >> 14) | (r3 << 18)) & 0x3FFFFFFu;
  st->r[4] = (r3 >> 8) & 0x3FFFFFFu;
  for (int i = 0; i < 5; ++i) {
    st->h[i] = 0u;
  }
  for (int i = 0; i < 4; ++i) {
    st->s[i] = load32_le(key + 16 + 4 * i);
  }
  st->buffer_used = 0u;
}

/*
 * Processa um bloco de 16 bytes (ou um bloco final menor com
 * `hibit` = 0 indicando que o caller ja inseriu o terminator 0x01
 * explicitamente no buffer). Atualiza h := (h + n) * r mod (2^130-5).
 */
static void poly1305_block(struct poly1305_state *st, const uint8_t block[16],
                           uint32_t hibit) {
  /* Carrega o bloco como 4 words 32-bit little-endian, depois quebra
   * em 5 limbs de 26 bits. O bit 129 (hibit) e adicionado ao topo. */
  uint32_t t0 = load32_le(block + 0);
  uint32_t t1 = load32_le(block + 4);
  uint32_t t2 = load32_le(block + 8);
  uint32_t t3 = load32_le(block + 12);

  st->h[0] += t0 & 0x3FFFFFFu;
  st->h[1] += ((t0 >> 26) | (t1 << 6)) & 0x3FFFFFFu;
  st->h[2] += ((t1 >> 20) | (t2 << 12)) & 0x3FFFFFFu;
  st->h[3] += ((t2 >> 14) | (t3 << 18)) & 0x3FFFFFFu;
  st->h[4] += (t3 >> 8) | hibit;

  /* Multiplicacao h * r mod (2^130 - 5). r e fixo em 5 limbs;
   * h tambem. Cada d[i] = sum_{j+k=i} h[j] * r[k] + carry. As
   * cross-terms apos o limb 4 (>= 2^130) sao reduzidas via *5
   * porque 2^130 ≡ 5 (mod 2^130-5). */
  uint64_t d0 = (uint64_t)st->h[0] * st->r[0] +
                (uint64_t)st->h[1] * (5u * st->r[4]) +
                (uint64_t)st->h[2] * (5u * st->r[3]) +
                (uint64_t)st->h[3] * (5u * st->r[2]) +
                (uint64_t)st->h[4] * (5u * st->r[1]);
  uint64_t d1 = (uint64_t)st->h[0] * st->r[1] +
                (uint64_t)st->h[1] * st->r[0] +
                (uint64_t)st->h[2] * (5u * st->r[4]) +
                (uint64_t)st->h[3] * (5u * st->r[3]) +
                (uint64_t)st->h[4] * (5u * st->r[2]);
  uint64_t d2 = (uint64_t)st->h[0] * st->r[2] +
                (uint64_t)st->h[1] * st->r[1] +
                (uint64_t)st->h[2] * st->r[0] +
                (uint64_t)st->h[3] * (5u * st->r[4]) +
                (uint64_t)st->h[4] * (5u * st->r[3]);
  uint64_t d3 = (uint64_t)st->h[0] * st->r[3] +
                (uint64_t)st->h[1] * st->r[2] +
                (uint64_t)st->h[2] * st->r[1] +
                (uint64_t)st->h[3] * st->r[0] +
                (uint64_t)st->h[4] * (5u * st->r[4]);
  uint64_t d4 = (uint64_t)st->h[0] * st->r[4] +
                (uint64_t)st->h[1] * st->r[3] +
                (uint64_t)st->h[2] * st->r[2] +
                (uint64_t)st->h[3] * st->r[1] +
                (uint64_t)st->h[4] * st->r[0];

  /* Carry propagation. */
  uint32_t c;
  c = (uint32_t)(d0 >> 26);
  st->h[0] = (uint32_t)d0 & 0x3FFFFFFu;
  d1 += c;
  c = (uint32_t)(d1 >> 26);
  st->h[1] = (uint32_t)d1 & 0x3FFFFFFu;
  d2 += c;
  c = (uint32_t)(d2 >> 26);
  st->h[2] = (uint32_t)d2 & 0x3FFFFFFu;
  d3 += c;
  c = (uint32_t)(d3 >> 26);
  st->h[3] = (uint32_t)d3 & 0x3FFFFFFu;
  d4 += c;
  c = (uint32_t)(d4 >> 26);
  st->h[4] = (uint32_t)d4 & 0x3FFFFFFu;
  /* Carry alem do bit 130 reduz via *5 (2^130 ≡ 5 mod p). */
  st->h[0] += c * 5u;
  c = st->h[0] >> 26;
  st->h[0] &= 0x3FFFFFFu;
  st->h[1] += c;
}

static void poly1305_update(struct poly1305_state *st, const uint8_t *data,
                            size_t data_len) {
  /* Drena o buffer existente primeiro, se houver. */
  if (st->buffer_used > 0u) {
    size_t want = 16u - st->buffer_used;
    if (data_len < want) {
      for (size_t i = 0u; i < data_len; ++i) {
        st->buffer[st->buffer_used + i] = data[i];
      }
      st->buffer_used += data_len;
      return;
    }
    for (size_t i = 0u; i < want; ++i) {
      st->buffer[st->buffer_used + i] = data[i];
    }
    /* hibit = 1u << 24 (bit 24 do limb 4, = bit 128 do numero,
     * conforme RFC: append 0x01 byte ao bloco de 16 bytes = bit 128). */
    poly1305_block(st, st->buffer, 1u << 24);
    data += want;
    data_len -= want;
    st->buffer_used = 0u;
  }
  /* Processa blocos completos diretamente do input. */
  while (data_len >= 16u) {
    poly1305_block(st, data, 1u << 24);
    data += 16u;
    data_len -= 16u;
  }
  /* Buferiza o restante (<16 bytes) para o proximo update ou finalize. */
  for (size_t i = 0u; i < data_len; ++i) {
    st->buffer[i] = data[i];
  }
  st->buffer_used = data_len;
}

static void poly1305_finish(struct poly1305_state *st,
                            uint8_t tag[POLY1305_TAG_SIZE]) {
  /* Bloco final (parcial): append byte 0x01, zero-pad ate 16 bytes,
   * processa SEM o hibit (porque o 0x01 ja foi inserido explicitamente
   * no buffer). */
  if (st->buffer_used > 0u) {
    st->buffer[st->buffer_used] = 0x01u;
    for (size_t i = st->buffer_used + 1u; i < 16u; ++i) {
      st->buffer[i] = 0u;
    }
    poly1305_block(st, st->buffer, 0u);
  }
  /* Carry propagation final em 5 limbs. */
  uint32_t c;
  c = st->h[1] >> 26;
  st->h[1] &= 0x3FFFFFFu;
  st->h[2] += c;
  c = st->h[2] >> 26;
  st->h[2] &= 0x3FFFFFFu;
  st->h[3] += c;
  c = st->h[3] >> 26;
  st->h[3] &= 0x3FFFFFFu;
  st->h[4] += c;
  c = st->h[4] >> 26;
  st->h[4] &= 0x3FFFFFFu;
  st->h[0] += c * 5u;
  c = st->h[0] >> 26;
  st->h[0] &= 0x3FFFFFFu;
  st->h[1] += c;

  /* Reducao final: se h >= p (2^130-5), subtrai p. Implementacao
   * constant-time via dual representation g = h + 5; se g[4] >= 2^26,
   * h = g. */
  uint32_t g0 = st->h[0] + 5u;
  c = g0 >> 26;
  g0 &= 0x3FFFFFFu;
  uint32_t g1 = st->h[1] + c;
  c = g1 >> 26;
  g1 &= 0x3FFFFFFu;
  uint32_t g2 = st->h[2] + c;
  c = g2 >> 26;
  g2 &= 0x3FFFFFFu;
  uint32_t g3 = st->h[3] + c;
  c = g3 >> 26;
  g3 &= 0x3FFFFFFu;
  uint32_t g4 = st->h[4] + c - (1u << 26);

  /* Mascara: g4 < 0 (i.e. bit 31 set) -> usa h; senao usa g. */
  uint32_t mask = (g4 >> 31) - 1u;
  uint32_t inv_mask = ~mask;
  st->h[0] = (st->h[0] & inv_mask) | (g0 & mask);
  st->h[1] = (st->h[1] & inv_mask) | (g1 & mask);
  st->h[2] = (st->h[2] & inv_mask) | (g2 & mask);
  st->h[3] = (st->h[3] & inv_mask) | (g3 & mask);
  st->h[4] = (st->h[4] & inv_mask) | (g4 & mask);

  /* Reagrupa 5 limbs de 26 bits em 4 words de 32 bits (radix 2^32). */
  uint32_t h0 = st->h[0] | (st->h[1] << 26);
  uint32_t h1 = (st->h[1] >> 6) | (st->h[2] << 20);
  uint32_t h2 = (st->h[2] >> 12) | (st->h[3] << 14);
  uint32_t h3 = (st->h[3] >> 18) | (st->h[4] << 8);

  /* tag = (h + s) mod 2^128. */
  uint64_t f = (uint64_t)h0 + (uint64_t)st->s[0];
  h0 = (uint32_t)f;
  f = (uint64_t)h1 + (uint64_t)st->s[1] + (f >> 32);
  h1 = (uint32_t)f;
  f = (uint64_t)h2 + (uint64_t)st->s[2] + (f >> 32);
  h2 = (uint32_t)f;
  f = (uint64_t)h3 + (uint64_t)st->s[3] + (f >> 32);
  h3 = (uint32_t)f;

  store32_le(tag + 0, h0);
  store32_le(tag + 4, h1);
  store32_le(tag + 8, h2);
  store32_le(tag + 12, h3);
}

int poly1305_mac(const uint8_t otk[POLY1305_KEY_SIZE], const uint8_t *msg,
                 size_t msg_len, uint8_t tag[POLY1305_TAG_SIZE]) {
  if (!otk || !tag) {
    return -1;
  }
  if (msg_len > 0u && !msg) {
    return -1;
  }
  struct poly1305_state st;
  poly1305_init(&st, otk);
  if (msg_len > 0u) {
    poly1305_update(&st, msg, msg_len);
  }
  poly1305_finish(&st, tag);
  wipe(&st, sizeof(st));
  return 0;
}

/* ============================================================
 * AEAD construction (RFC 8439 §2.8).
 * ============================================================ */

static void poly1305_pad16_into(struct poly1305_state *st, size_t len) {
  /* RFC 8439: depois de aad e depois de ct, pad com zero bytes ate
   * o proximo multiplo de 16. Implementado como N updates de zero. */
  size_t pad = (16u - (len % 16u)) % 16u;
  if (pad == 0u) {
    return;
  }
  static const uint8_t k_zero[16] = {0};
  poly1305_update(st, k_zero, pad);
}

/*
 * Helper interno: deriva OTK do bloco 0, computa o tag sobre
 * (aad || pad || ct || pad || u64le(aad_len) || u64le(ct_len))
 * e zera a OTK ao final.
 */
static int compute_aead_tag(const uint8_t key[CHACHA20_KEY_SIZE],
                            const uint8_t nonce[CHACHA20_NONCE_SIZE],
                            const uint8_t *aad, size_t aad_len,
                            const uint8_t *ct, size_t ct_len,
                            uint8_t tag[POLY1305_TAG_SIZE]) {
  uint8_t otk_block[CHACHA20_BLOCK_SIZE];
  if (chacha20_block(key, 0u, nonce, otk_block) != 0) {
    wipe(otk_block, sizeof(otk_block));
    return -1;
  }
  struct poly1305_state st;
  poly1305_init(&st, otk_block); /* OTK = primeiros 32 bytes do bloco. */
  if (aad_len > 0u) {
    poly1305_update(&st, aad, aad_len);
  }
  poly1305_pad16_into(&st, aad_len);
  if (ct_len > 0u) {
    poly1305_update(&st, ct, ct_len);
  }
  poly1305_pad16_into(&st, ct_len);
  uint8_t len_block[16];
  store64_le(len_block + 0, (uint64_t)aad_len);
  store64_le(len_block + 8, (uint64_t)ct_len);
  poly1305_update(&st, len_block, sizeof(len_block));
  poly1305_finish(&st, tag);
  wipe(&st, sizeof(st));
  wipe(otk_block, sizeof(otk_block));
  wipe(len_block, sizeof(len_block));
  return 0;
}

int chacha20_poly1305_encrypt(const uint8_t key[CHACHA20_KEY_SIZE],
                              const uint8_t nonce[CHACHA20_NONCE_SIZE],
                              const uint8_t *aad, size_t aad_len,
                              const uint8_t *plaintext, size_t pt_len,
                              uint8_t *ciphertext,
                              uint8_t tag[CHACHA20_POLY1305_TAG_SIZE]) {
  if (!key || !nonce || !tag) {
    return -1;
  }
  if (pt_len > 0u && (!plaintext || !ciphertext)) {
    return -1;
  }
  if (aad_len > 0u && !aad) {
    return -1;
  }
  /* Encrypt plaintext primeiro, depois autentica ciphertext.
   * Counter inicial = 1 (RFC 8439 §2.8) porque o bloco 0 e reservado
   * para derivar a OTK Poly1305. */
  if (pt_len > 0u) {
    if (chacha20_encrypt(key, 1u, nonce, plaintext, ciphertext, pt_len) != 0) {
      return -1;
    }
  }
  if (compute_aead_tag(key, nonce, aad, aad_len, ciphertext, pt_len, tag) !=
      0) {
    /* Falha ao computar tag — limpa o ciphertext para nao fornecer
     * dado parcialmente cifrado sem MAC. */
    if (pt_len > 0u && ciphertext) {
      wipe(ciphertext, pt_len);
    }
    return -1;
  }
  return 0;
}

int chacha20_poly1305_decrypt(const uint8_t key[CHACHA20_KEY_SIZE],
                              const uint8_t nonce[CHACHA20_NONCE_SIZE],
                              const uint8_t *aad, size_t aad_len,
                              const uint8_t *ciphertext, size_t ct_len,
                              const uint8_t tag[CHACHA20_POLY1305_TAG_SIZE],
                              uint8_t *plaintext) {
  if (!key || !nonce || !tag) {
    return -1;
  }
  if (ct_len > 0u && (!ciphertext || !plaintext)) {
    return -1;
  }
  if (aad_len > 0u && !aad) {
    return -1;
  }
  /* Recomputa tag sobre o ciphertext recebido e compara em tempo
   * constante. Verificacao ANTES de decifrar — fail-closed se tag
   * invalido (nao revela plaintext parcial). */
  uint8_t computed_tag[POLY1305_TAG_SIZE];
  if (compute_aead_tag(key, nonce, aad, aad_len, ciphertext, ct_len,
                       computed_tag) != 0) {
    wipe(computed_tag, sizeof(computed_tag));
    return -1;
  }
  int rc = crypt_constant_time_compare(computed_tag, tag, POLY1305_TAG_SIZE);
  wipe(computed_tag, sizeof(computed_tag));
  if (rc != 0) {
    return -1;
  }
  /* Tag valido: agora decifra. ChaCha20 e simetrico — encrypt com a
   * mesma chave/counter/nonce e a operacao inversa. */
  if (ct_len > 0u) {
    if (chacha20_encrypt(key, 1u, nonce, ciphertext, plaintext, ct_len) != 0) {
      /* Algo deu errado no decrypt mesmo apos tag valido (counter
       * overflow no caminho de ct). Limpa o plaintext para nao
       * deixar dado parcial. */
      wipe(plaintext, ct_len);
      return -1;
    }
  }
  return 0;
}
